namespace BoldAspect.CLI
{
    public enum ElementType : byte
    {
        End,
        Void,
        Boolean,
        Char,
        I1,
        U1,
        I2,
        U2,
        I4,
        U4,
        I8,
        U8,
        R4,
        R8,
        String,
        Ptr,
        Byref,
        Valuetype,
        Class,
        Var,
        Array,
        Genericinst,
        Typedbyref = 0x16,
        I = 0x18,
        U = 0x19,
        Fnptr = 0x1B,
        Object = 0x1C,
        Szarray = 0x1D,
        Mvar = 0x1E,
        Cmod_reqd = 0x1F,
        Cmod_opt = 0x20,
        Internal = 0x21,
        Modifier = 0x40,
        Sentinel = 0x41,
        Pinned = 0x45,
        SystemType = 0x50,
        BoxedObject = 0x51,
        Reserved = 0x52,
        Field = 0x53,
        Property = 0x54,
        Enum = 0x55,
    }
}